### ISSUE TITLE
@tomlogan501 - AWS/CPR Blog

### ISSUE THREAD

**Issue by dniewinski** [clearpathrobotics/cpr_gazebo#14]
Hello @tomlogan501,

Clearpath and Amazon are working on developing a blog article about the recently launched AWS Robomaker Simulations.  We are hoping to highlight a few users from the community and their experiences using the simulations so far.  I noticed that you have forked the git repo and were wondering if you've had some time to explore or make use of the simulations.  If so and you're interested in being featured on our blog, let me know and I can send over a short list of questions.

Thanks,

Dave

**Comment by tomlogan501** [comment]
Hello @dniewinski,
For my work at ENSTA paris in the research lab U2IS, I merged a lot of simulation to train the students on the husky before the real one. I also made a world for the ERL event 2020: [LINK](https://github.com/tomlogan501/erl_simulations).
I can answer your questions if you want.

Thomas

**Comment by cbogdon** [comment]
Hi @tomlogan501 , 
What email address can you be reached at?  I'd be happy to introduce you to the AWS Robomaker team that is developing the blog article.  They are very much interested in learning more about your experiences working with the simulations for the article.
Thanks, 
Chris

**Comment by tomlogan501** [comment]
Hi @cbogdon ,
You can reach me on jobs@reebot.tech
