### ISSUE TITLE
Ask some questions about the world env mesh file

### ISSUE THREAD

**Issue by KairongWu** [clearpathrobotics/cpr_gazebo#20]
I run the code it works very well.
I want to ask you some questions about how to build the sim world.
Such as the office world ,it was just a .dae file.
Which software you use to create so amazing models.

**Comment by civerachb-cpr** [comment]
Collada files (.dae) can be edited/created in a lot of different tools.  I believe the developer who made these environments used Blender.

**Comment by KairongWu** [comment]
Thank you for your answer！
Because I use solidworks to build the env mesh, but the STL mesh file have too many
points and faces. So it make the gazebo simulation too slow, and I see your .dae file work
very good! Amazing!

**Comment by civerachb-cpr** [comment]
Glad to help.
