### ISSUE TITLE
License files

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [clearpathrobotics/cpr_gazebo#3]
Hi,

Thank you for the amazing worlds! This repository looks quite useful for testing robotic applications

However, I see no license attached to the repo
Would it be possible to clarify what license the package is distributed with?

Thank you in advance

**Comment by civerachb-cpr** [comment]
These maps are released under the BSD license.  I've added license files to each ROS package to make it clearer (though the license had been set in the relevant package.xml files already)
