### ISSUE TITLE
@iamshyamganatra - AWS/CPR Blog

### ISSUE THREAD

**Issue by dniewinski** [clearpathrobotics/cpr_gazebo#8]
Hello @iamshyamganatra,

Clearpath and Amazon are working on developing a blog article about the recently launched AWS Robomaker Simulations.  We are hoping to highlight a few users from the community and their experiences using the simulations so far.  I noticed that you have forked the git repo and were wondering if you've had some time to explore or make use of the simulations.  If so and you're interested in being featured on our blog, let me know and I can send over a short list of questions.

Thanks,

Dave

**Comment by ganatrask** [comment]
Hello @dniewinski,

I have been using these simulations for the research work at my organization at [KamdhenuRobotics.com](https://kamdhenurobotics.com/). I have tried the Office simulation and the Farm simulation on my local machine never got a chance to try on AWS robomaker, specifically, the solar farm simulations are very helpful for us as we have been working on developing an application for solar farm robot. 

Thanks,
Shyam.

**Comment by cbogdon** [comment]
Hi @iamshyamganatra 
What email address can you be reached at?  I'd be happy to introduce you to the AWS Robomaker team that is developing the blog article.  They are very much interested in learning more about your experiences working with the simulations for the article.
Thanks, 
Chris

**Comment by ganatrask** [comment]
Hi @cbogdon ,
I would also be happy to get connected with the AWS Robomaker team, you can reach me at shyam@kamdhenurobotics.com .

Thanks,
Shyam
